# Generated by Django 4.2 on 2023-05-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_des', models.TextField()),
                ('movie_rating', models.IntegerField()),
            ],
        ),
    ]
