# Generated by Django 4.2 on 2023-05-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptwo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_rating',
            field=models.FloatField(),
        ),
    ]
