# Generated by Django 4.2 on 2023-06-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptwo', '0002_alter_movies_movie_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_id', models.IntegerField()),
                ('series_name', models.CharField(max_length=100)),
                ('series_des', models.TextField()),
                ('series_rating', models.FloatField()),
            ],
        ),
    ]
