# Generated by Django 4.2 on 2023-06-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appthree', '0002_alter_suggestinfo_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestinfo',
            name='rating',
            field=models.FloatField(),
        ),
    ]
